directories:
  excluded_patterns:
  - '*.tmp'
  - 'node_modules/**'
  - '.git/**'
  markdown_root: ./docs

mapping:
  strategy: frontmatter  # or filename

notion:
  parent_page_id: "" # Set via NOTION_MD_SYNC_NOTION_PARENT_PAGE_ID env var
  token: "" # Set via NOTION_MD_SYNC_NOTION_TOKEN env var

sync:
  conflict_resolution: newer  # newer, notion_wins, markdown_wins
  direction: push  # push, pull, bidirectional

# Performance optimization settings
# Based on extensive testing showing 26% performance improvement
performance:
  # Worker count: 0 = auto-detect (recommended)
  # - Small workspaces (<5 pages): Uses page count
  # - Medium workspaces (5-14 pages): Uses 20 workers
  # - Large workspaces (15+ pages): Uses 30 workers
  workers: 0
  
  # Multi-client mode (experimental)
  # Standard single client usually performs best
  use_multi_client: false
  
  # Number of HTTP clients when multi-client is enabled
  client_count: 3