notion:
  token: "your_notion_integration_token_here"
  parent_page_id: "your_parent_page_id_here"

sync:
  direction: "push"  # push, pull, or bidirectional
  conflict_resolution: "newer"  # newer, notion_wins, markdown_wins

directories:
  markdown_root: "./"
  excluded_patterns:
    - "node_modules/**"
    - ".git/**"
    - "*.tmp"

mapping:
  strategy: "filename"  # filename or frontmatter